version: "3.9"
services:

    clash:
        image: dreamacro/clash
        restart: always
        ports:
            - 7890:7890
            - 7891:7891
            - 9090:9090
        volumes:
            - ./config:/root/.config/clash

    yacd:
        image: haishanh/yacd
        restart: always
        ports:
            - 1234:80

